- remove duplicate dependency in Gemfile
Shmekal/GBuyCruelWord pull request #4
Opened 2016-11-25 02:27 UTC by Shmekal

Commit description:
- remove all non-rspec test-files(scripts)
- rename spec/basic_spec.rb to spec/register_spec.rb and move it to spec/features/
- most important: reorganize register_spec.rb and respective class
  note: not sure if split checks by register is worth doing at all as register of initial query affects nothing - register of Title and Description depends only on the particular search result and URL is always downcase

Notes:
Такой громоздкой коммит получился. Впоследующем лучше разбивать на логические части?

2016-11-28 15:28 UTC, nonkor requested changes
Strange PR name, especially if know there is no gemfile touching :)
But in general - good PR, taka a look on my small issues.

2016-11-28 15:28 UTC, nonkor commented on spec/features/register_spec.rb
> +    # not sure if curly bracket syntax is acceptable
yep, acceptable

2016-11-28 15:28 UTC, nonkor commented on spec/features/register_spec.rb
> +        expect(@page.first_result_url).to include('monster')
why downcased version here?

2016-11-28 15:28 UTC, nonkor commented on spec/features/register_spec.rb
> +        expect(@page.first_result_title).to include('Monster')
upcase?

2016-11-28 15:28 UTC, nonkor commented on spec/features/register_spec.rb
> +        expect(@page.first_result_description).to include('Monster')
upcase?

2016-11-28 15:28 UTC, nonkor commented on lib/page.rb
> +        when :title
good for now, but would be better to wrap them into page objects in future.

2016-11-28 15:30 UTC, nonkor commented
About the commit: this seems ok for me. But yeah, makes sense to granulate them by logical parts.

2016-11-28 22:09 UTC, Shmekal commented on spec/features/register_spec.rb
> +        expect(@page.first_result_url).to include('monster')
the thing is that url register is always downcased. knowing that we always expect it that way(downcase)

2016-11-28 22:18 UTC, Shmekal commented on spec/features/register_spec.rb
> +        expect(@page.first_result_title).to include('Monster')
@nonkor , yes. the register in description and title doesn't correlate with the initial query(keyword) register. so as long as we check for hardcoded values this check expects perticular register. the test will become falling once search engine changes the first result. and this is the weak point I don't know how to deal with. maybe we should refuse doing register checks for the title and description sections? but probably there's already a conventional solution for such cases.

2016-11-28 22:19 UTC, Shmekal commented on spec/features/register_spec.rb
> +        expect(@page.first_result_description).to include('Monster')
@nonkor see the :41 comment

2016-11-28 22:22 UTC, Shmekal commented on lib/page.rb
> +        when :title
@nonkor attr_accessor's, right?

2016-11-28 23:37 UTC, Shmekal commented
@nonkor not sure how we go on. but here's the last commit description:
- remove duplicate in Gemfile(finally)
- split spec into two by the case(register) principle

2016-11-29 11:10 UTC, nonkor commented on lib/page.rb
> +        when :title
no, I mean [page object pattern](https://habrahabr.ru/company/wapstart/blog/138674/). I would recommend to read that doc.

2016-11-29 11:21 UTC, nonkor commented on spec/features/register_spec.rb
> +        expect(@page.first_result_title).to include('Monster')
I would explain it by a call, much quicker.

2016-12-16 09:27 UTC, nonkor approved these changes
I like it. Great job!
Next step: create page objects by to page object pattern. Good implementation of this pattern for capybara is [site_prism](https://github.com/natritmeyer/site_prism)

2016-12-16 09:27 UTC, nonkor commented on spec/features/basic_search_spec.rb
> +
You like empty lines so much. I recommend to use [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide).

2016-12-16 16:33 UTC, merged